services:
  spring-training-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_SHEETS_CREDENTIALS=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json:ro
